<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: 

_The Input Layer is what receives input from our dataset. Sometimes it is called the visible layer because it's the only part that is exposed to our data and that our data interacts with directly. Typically node maps are drawn with one input node for each of the different inputs/features/columns of our dataset that will be passed to the network._

### Hidden Layer:

_Layers after the input layer are called Hidden Layers. This is because they cannot be accessed except through the input layer. They're inside of the network and they perform their functions, but we don't directly interact with them._

### Output Layer:

_The purpose of the output layer is to output a vector of values that is in a format that is suitable for the type of problem that we're trying to address._

### Neuron:

_An artificial neuron is a mathematical function conceived as a model of biological neurons, a neural network. Artificial neurons are elementary units in an artificial neural network. The artificial neuron receives one or more inputs (representing excitatory postsynaptic potentials and inhibitory postsynaptic potentials at neural dendrites) and sums them to produce an output (or activation, representing a neuron's action potential which is transmitted along its axon). Usually each input is separately weighted, and the sum is passed through a non-linear function known as an activation function or transfer function. The transfer functions usually have a sigmoid shape, but they may also take the form of other non-linear functions, piecewise linear functions, or step functions. They are also often monotonically increasing, continuous, differentiable and bounded. The thresholding function has inspired building logic gates referred to as threshold logic; applicable to building logic circuits resembling brain processing. For example, new devices such as memristors have been extensively used to develop such logic in recent times._

### Weight:

_A weight represent the strength of the connection between units. If the weight from node 1 to node 2 has greater magnitude, it means that neuron 1 has greater influence over neuron 2. A weight brings down the importance of the input value. Weights near zero means changing this input will not change the output. Negative weights mean increasing this input will decrease the output. A weight decides how much influence the input will have on the output._

<img align="center" src="https://cdn-images-1.medium.com/max/1600/0*S-FQtnzUxIBFpObg.png" width=500>
<br></br>
<br></br>

### Activation Function:

_Activation functions are used to introduce non-linearity to neural networks. It squashes the values in a smaller range viz. a Sigmoid activation function squashes values between a range 0 to 1. There are many activation functions used in deep learning industry and ReLU, SeLU and TanH are preferred over sigmoid activation function. In this article I have explained the different activation functions available._

<img align="center" src="https://cdn-images-1.medium.com/max/1600/1*p_hyqAtyI8pbt2kEl6siOQ.png" width=800>
<br></br>
<br></br>

### Node Map:

_A visual diagram of the architecture or "topology" of our neural network. It's kind of like a flow chart in that it shows the path from inputs to outputs. They are usually color coded and help us understand at a very high level, some of the differences in architecture between kinds of neural networks. Just like with all the areas of machine learning that we have studied before there is a "[zoo](http://www.asimovinstitute.org/neural-network-zoo/)" of neural network architectures:_

![Neural Network Zoo](http://www.asimovinstitute.org/wp-content/uploads/2016/09/neuralnetworks.png)

### Perceptron:

_A single node or neuron of a neural network with nothing else. It can take any number of inputs and spit out an output._


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here: 
_The nodes of the input layer are passive, meaning they do not modify the data. They receive a single value on their input, and duplicate the value to_

![](https://www.dspguide.com/graphics/F_26_5.gif)

_their multiple outputs. In comparison, the nodes of the hidden and output layer are active. This means they modify the data as shown in Fig. 26-6. The variables: X11,X12…X115 hold the data to be evaluated (see Fig. 26-5). For example, they may be pixel values from an image, samples from an audio signal, stock market prices on successive days, etc. They may also be the output of some other algorithm, such as the classifiers in our cancer detection example: diameter, brightness, edge sharpness, etc._



_Each value from the input layer is duplicated and sent to all of the hidden nodes. This is called a fully interconnected structure. As shown in Fig. 26-6, the values entering a hidden node are multiplied by weights, a set of predetermined numbers stored in the program. The weighted inputs are then added to produce a single number. This is shown in the diagram by the symbol, ∑. Before leaving the node, this number is passed through a nonlinear mathematical function called a sigmoid. This is an "s" shaped curve that limits the node's output. That is, the input to the sigmoid is a value between -∞ and +∞, while its output can only be between 0 and 1._

_The outputs from the hidden layer are represented in the flow diagram (Fig 26-5) by the variables: X21,X22,X23 and X24. Just as before, each of these values is duplicated and applied to the next layer. The active nodes of the output layer combine and modify the data to produce the two output values of this network, X31 and X32._

_Neural networks can have any number of layers, and any number of nodes per layer. Most applications use the three layer structure with a maximum of a few hundred input nodes. The hidden layer is usually about 10% the size of the input layer. In the case of target detection, the output layer only needs a single node. The output of this node is thresholded to provide a positive or negative indication of the target's presence or absence in the input data._

_Table 26-1 is a program to carry out the flow diagram of Fig. 26-5. The key point is that this architecture is very simple and very generalized. This same flow diagram can be used for many problems, regardless of their particular quirks. The ability of the neural network to provide useful data manipulation lies in the proper selection of the weights. This is a dramatic departure from conventional information processing where solutions are described in step-by-step procedures._

_As an example, imagine a neural network for recognizing objects in a sonar signal. Suppose that 1000 samples from the signal are stored in a computer. How does the computer determine if these data represent a submarine, whale, undersea mountain, or nothing at all? Conventional DSP would approach this problem with mathematics and algorithms, such as correlation and frequency spectrum analysis. With a neural network, the 1000 samples are simply fed into the input layer, resulting in values popping from the output layer. By selecting the proper weights, the output can be configured to report a wide range of information. For instance, there might be outputs for: submarine (yes/no), whale (yes/no), undersea mountain (yes/no), etc._

![](https://www.dspguide.com/graphics/F_26_6.gif)


## Write your own perceptron code that can correctly classify a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [12]:
##### Your Code Here #####
import numpy as np

np.random.seed(812)

inputs = np.array([
    [0,0,1],
    [1,0,1],
    [0,1,1],
    [1,1,1]   
])

ground_truth = [[1], [1], [1], [0]]

In [13]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [14]:
weights = 2 *  -  np.random.random((3,1)) - 1
weights

array([[-2.0099616 ],
       [-2.21185521],
       [-1.91497438]])

In [15]:
weighted_sum = np.dot(inputs, weights)

weighted_sum

array([[-1.91497438],
       [-3.92493598],
       [-4.12682959],
       [-6.13679119]])

In [16]:
activated_output = sigmoid(weighted_sum)

activated_output

array([[0.12842304],
       [0.01936115],
       [0.01587778],
       [0.00215719]])

In [17]:
error = ground_truth - activated_output
error

array([[ 0.87157696],
       [ 0.98063885],
       [ 0.98412222],
       [-0.00215719]])

In [18]:
adjustments = error * sigmoid_derivative(activated_output)
adjustments

array([[ 0.2169983 ],
       [ 0.24513674],
       [ 0.24601505],
       [-0.0005393 ]])

In [19]:
weights += np.dot(inputs.T, adjustments)

weights

array([[-1.76536416],
       [-1.96637946],
       [-1.20736358]])

In [20]:
for iteration in range(10000):
    
    # Weighted sum of inputs/weights
    weighted_sum = np.dot(inputs, weights)
    
    #Activate
    activated_output = sigmoid(weighted_sum)
    
    # Calculate the error
    error = ground_truth - activated_output
    
    # Adjustments
    adjustments = error * sigmoid_derivative(activated_output)
    
    weights += np.dot(inputs.T, adjustments)
    
    print("Weights after training")
    print(weights)
    
    print("Output after training")
    print(activated_output)

Weights after training
[[-1.52945078]
 [-1.72829517]
 [-0.54165702]]
Output after training
[[0.23016787]
 [0.04867326]
 [0.04016586]
 [0.00711007]]
Weights after training
[[-1.31360186]
 [-1.50767461]
 [ 0.05310784]]
Output after training
[[0.3678022 ]
 [0.11193687]
 [0.09364227]
 [0.02189405]]
Weights after training
[[-1.13593509]
 [-1.32155874]
 [ 0.54565127]]
Output after training
[[0.51327384]
 [0.22088886]
 [0.18929973]
 [0.05906872]]
Weights after training
[[-1.01214443]
 [-1.18660263]
 [ 0.91956653]]
Output after training
[[0.63312607]
 [0.35656974]
 [0.31520259]
 [0.12877399]]
Weights after training
[[-0.94230738]
 [-1.10524709]
 [ 1.18742007]]
Output after training
[[0.71495377]
 [0.47687204]
 [0.43363487]
 [0.21768975]]
Weights after training
[[-0.91346123]
 [-1.06585571]
 [ 1.3789942 ]]
Output after training
[[0.76627933]
 [0.5609732 ]
 [0.52053169]
 [0.29731127]]
Weights after training
[[-0.91144229]
 [-1.05445456]
 [ 1.52131138]]
Output after training
[[0.79882942]
 [0.614

## Implement your own Perceptron Class and use it to classify a binary dataset like: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 
- [Titanic](https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv)
- [A two-class version of the Iris dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv)

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [ ]:
##### Your Code Here #####
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv', header=None)


## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?