<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Perceptron on XOR Gates](#Q2)
3. [Multilayer Perceptron](#Q3)
4. [Keras MMP](#Q4)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**

_An artificial neuron is a mathematical function conceived as a model of biological neurons, a neural network. Artificial neurons are elementary units in an artificial neural network. The artificial neuron receives one or more inputs (representing excitatory postsynaptic potentials and inhibitory postsynaptic potentials at neural dendrites) and sums them to produce an output (or activation, representing a neuron's action potential which is transmitted along its axon). Usually each input is separately weighted, and the sum is passed through a non-linear function known as an activation function or transfer function. The transfer functions usually have a sigmoid shape, but they may also take the form of other non-linear functions, piecewise linear functions, or step functions. They are also often monotonically increasing, continuous, differentiable and bounded. The thresholding function has inspired building logic gates referred to as threshold logic; applicable to building logic circuits resembling brain processing. For example, new devices such as memristors have been extensively used to develop such logic in recent times._

- **Input Layer:**

_The Input Layer is what receives input from our dataset. Sometimes it is called the visible layer because it's the only part that is exposed to our data and that our data interacts with directly. Typically node maps are drawn with one input node for each of the different inputs/features/columns of our dataset that will be passed to the network._

- **Hidden Layer:**

_Layers after the input layer are called Hidden Layers. This is because they cannot be accessed except through the input layer. They're inside of the network and they perform their functions, but we don't directly interact with them._

- **Output Layer:**

_The purpose of the output layer is to output a vector of values that is in a format that is suitable for the type of problem that we're trying to address._

- **Activation:**

_Activation functions are used to introduce non-linearity to neural networks. It squashes the values in a smaller range viz. a Sigmoid activation function squashes values between a range 0 to 1. There are many activation functions used in deep learning industry and ReLU, SeLU and TanH are preferred over sigmoid activation function. In this article I have explained the different activation functions available._

<img align="center" src="https://cdn-images-1.medium.com/max/1600/1*p_hyqAtyI8pbt2kEl6siOQ.png" width=800>
<br></br>
<br></br>


- **Backpropagation:**

_Iterative, recursive and efficient method for calculating the weights updates to improve the network until it is able to perform the task for which it is being trained. It is closely related to the Gauss–Newton algorithm._

_Backpropagation requires the derivatives of activation functions to be known at network design time. Automatic differentiation is a technique that can automatically and analytically provide the derivatives to the training algorithm. In the context of learning, backpropagation is commonly used by the gradient descent optimization algorithm to adjust the weight of neurons by calculating the gradient of the loss function; backpropagation computes the gradient(s), whereas (stochastic) gradient descent uses the gradients for training the model (via optimization)._

## 2. Perceptron on AND Gates <a id="Q3=2"></a>

Create a perceptron class that can model the behavior of an AND gate. You can use the following table as your training data:

|x1	|x2|x3|	y|
|---|---|---|---|
1|	1|	1|	1|
1|	0|	1|	0|
0|	1|	1|	0|
0|	0|	1|	0|

In [1]:
import numpy as np

np.random.seed(38)


# Inputs
inputs = np.array(([1, 1, 1],
                   [1, 0, 1],
                   [0, 1, 1],
                   [0, 0, 1]), dtype=float)

# Ground Truth
ground_truth = np.array(([1],
                         [0],
                         [0],
                         [0]), dtype=float)

In [2]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [3]:
weights = 2 *  -  np.random.random((3,1)) - 1
weights

array([[-1.76954624],
       [-2.71941569],
       [-2.88839927]])

In [4]:
weighted_sum = np.dot(inputs, weights)

weighted_sum

array([[-7.3773612 ],
       [-4.65794551],
       [-5.60781496],
       [-2.88839927]])

In [5]:
for iteration in range(10000):
    
    # Weighted sum of inputs/weights
    weighted_sum = np.dot(inputs, weights)
    
    #Activate
    activated_output = sigmoid(weighted_sum)
    
    # Calculate the error
    error = ground_truth - activated_output
    
    # Adjustments
    adjustments = error * sigmoid_derivative(activated_output)
    
    weights += np.dot(inputs.T, adjustments)
    
    print("Weights after training")
    print(weights)
    
    print("Output after training")
    print(activated_output)

Weights after training
[[-1.52205162]
 [-2.47048585]
 [-2.65499192]]
Output after training
[[0.00062486]
 [0.00939679]
 [0.00365566]
 [0.05273002]]
Weights after training
[[-1.27615338]
 [-2.22228689]
 [-2.42697353]]
Output after training
[[0.00129554]
 [0.01511193]
 [0.00590826]
 [0.065682  ]]
Weights after training
[[-1.03283223]
 [-1.97532267]
 [-2.20627317]]
Output after training
[[0.00266359]
 [0.02405351]
 [0.00947798]
 [0.08113882]]
Weights after training
[[-0.79361281]
 [-1.73043739]
 [-1.99555088]]
Output after training
[[0.00540814]
 [0.03772035]
 [0.01504432]
 [0.09918857]]
Weights after training
[[-0.56078   ]
 [-1.48901841]
 [-1.79840876]]
Output after training
[[0.01077598]
 [0.05791257]
 [0.02352264]
 [0.11967084]]
Weights after training
[[-0.33756926]
 [-1.25326165]
 [-1.61952906]]
Output after training
[[0.02087295]
 [0.08633817]
 [0.03600504]
 [0.14204488]]
Weights after training
[[-0.12818113]
 [-1.0264156 ]
 [-1.46454673]]
Output after training
[[0.03877771]
 [0.123

## 3. Multilayer Perceptron <a id="Q3"></a>

Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights.
Your network must have one hidden layer.
You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights.
Train your model on the Heart Disease dataset from UCI:



In [6]:
cd Documents/GitHub/DS-Unit-4-Sprint-2-Neural-Networks/Sprint-Challenge

/home/seek/Documents/GitHub/DS-Unit-4-Sprint-2-Neural-Networks/Sprint-Challenge


In [16]:
import pandas as pd
dataset = pd.read_csv('heart.csv')

In [17]:
dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [18]:
X = dataset.values[:,0:13]
print(X.shape)
print(X)

(303, 13)
[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]


In [19]:
y = dataset.values[:,-1]
print(y.shape)
print(y)

(303,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
# fix random seed for reproducibility
np.random.seed(38)

In [21]:
model = Sequential()

In [22]:
model.add(Dense(1, input_dim=13, activation="sigmoid"))

In [23]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [24]:
model.fit(X, y, epochs=150, batch_size=32)

Epoch 1/150
303/303 [==============================] - 0s 203us/sample - loss: 57.2469 - acc: 0.4554
Epoch 2/150
303/303 [==============================] - 0s 55us/sample - loss: 54.0286 - acc: 0.4554
Epoch 3/150
303/303 [==============================] - 0s 56us/sample - loss: 50.8730 - acc: 0.4554
Epoch 4/150
303/303 [==============================] - 0s 46us/sample - loss: 47.6200 - acc: 0.4554
Epoch 5/150
303/303 [==============================] - 0s 41us/sample - loss: 44.4837 - acc: 0.4554
Epoch 6/150
303/303 [==============================] - 0s 43us/sample - loss: 41.3425 - acc: 0.4554
Epoch 7/150
303/303 [==============================] - 0s 42us/sample - loss: 38.0275 - acc: 0.4554
Epoch 8/150
303/303 [==============================] - 0s 43us/sample - loss: 34.9572 - acc: 0.4554
Epoch 9/150
303/303 [==============================] - 0s 45us/sample - loss: 31.7052 - acc: 0.4554
Epoch 10/150
303/303 [==============================] - 0s 41us/sample - loss: 28.5603 - acc: 0.455

In [25]:
sum(y) / len(y) # Predicting target is 70%

0.5445544554455446

In [26]:
scores = model.evaluate(X,y)
print(f"{model.metrics_names[1]}: {scores[1]*100}")

303/303 [==============================] - 0s 97us/sample - loss: 2.1570 - acc: 0.7129
acc: 71.28713130950928


In [28]:
model = Sequential()
model.add(Dense(1, input_dim=13, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=150)

Epoch 1/150
303/303 [==============================] - 0s 206us/sample - loss: 98.3989 - acc: 0.4554
Epoch 2/150
303/303 [==============================] - 0s 48us/sample - loss: 95.2105 - acc: 0.4554
Epoch 3/150
303/303 [==============================] - 0s 46us/sample - loss: 92.0333 - acc: 0.4554
Epoch 4/150
303/303 [==============================] - 0s 39us/sample - loss: 88.8044 - acc: 0.4554
Epoch 5/150
303/303 [==============================] - 0s 57us/sample - loss: 85.6967 - acc: 0.4554
Epoch 6/150
303/303 [==============================] - 0s 45us/sample - loss: 82.5172 - acc: 0.4554
Epoch 7/150
303/303 [==============================] - 0s 46us/sample - loss: 79.3929 - acc: 0.4554
Epoch 8/150
303/303 [==============================] - 0s 45us/sample - loss: 76.1961 - acc: 0.4554
Epoch 9/150
303/303 [==============================] - 0s 47us/sample - loss: 73.0131 - acc: 0.4554
Epoch 10/150
303/303 [==============================] - 0s 47us/sample - loss: 69.9261 - acc: 0.455

In [29]:
# evaluate the model
scores = model.evaluate(X, y)
print(f"{model.metrics_names[1]}: {scores[1]*100}")

303/303 [==============================] - 0s 90us/sample - loss: 2.9956 - acc: 0.5512
acc: 55.115509033203125


In [30]:
model_improved = Sequential()

# Input + 1 First Hidden
model_improved.add(Dense(10, input_dim=13, activation='relu'))
# Hidden
model_improved.add(Dense(3, activation='sigmoid'))
# Output
model_improved.add(Dense(1, activation='sigmoid'))

model_improved.compile(loss='binary_crossentropy', 
                       optimizer='adam',
                       metrics=['accuracy'])

model_improved.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 33        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 4         
Total params: 177
Trainable params: 177
Non-trainable params: 0
_________________________________________________________________


## 4. Keras MMP <a id="Q4"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 5 parameters in order to get a 3 on this section.

In [33]:
import keras
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy as np
# fix random seed for reproducibility
np.random.seed(38)

Using TensorFlow backend.


In [35]:
df = pd.read_csv('heart.csv')


df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [36]:
from sklearn.model_selection import StratifiedKFold

# fix random seed for reproducibility
seed = 38
np.random.seed(seed)


# split into input (X) and output (y) variables
X = df.drop(columns=['target']).values
y = df['target'].values

# define 5-fold cross validation test harness
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
cvscores = []
for train, test in kfold.split(X, y):
  # create model
  model = Sequential()
  model.add(Dense(12, input_dim=13, activation='relu'))
  model.add(Dense(8, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  # Compile model
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) # Fit the model
  model.fit(X[train], y[train], epochs=150, batch_size=10, verbose=0)
  # evaluate the model
  scores = model.evaluate(X[test], y[test], verbose=0)
  print(f'{model.metrics_names[1]}: {(scores[1]*100):.2f}%') 
  cvscores.append(scores[1]*100)
print(f'{np.mean(cvscores):.2f}% +/- {np.std(cvscores):.2f}%')

W0719 13:13:56.093108 140707968808768 deprecation_wrapper.py:119] From /home/seek/anaconda3/envs/U4-S2-NNF/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0719 13:13:56.094331 140707968808768 deprecation_wrapper.py:119] From /home/seek/anaconda3/envs/U4-S2-NNF/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0719 13:13:56.096407 140707968808768 deprecation_wrapper.py:119] From /home/seek/anaconda3/envs/U4-S2-NNF/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0719 13:13:56.134510 140707968808768 deprecation_wrapper.py:119] From /home/seek/anaconda3/envs/U4-S2-NNF/lib/python3.7/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please

acc: 54.10%
acc: 67.21%
acc: 54.10%
acc: 83.33%
acc: 45.00%
60.75% +/- 13.33%


In [38]:
from sklearn.model_selection import GridSearchCV
from keras.wrappers.scikit_learn import KerasClassifier

# fix random seed for reproducibility
seed = 38
np.random.seed(seed)


# split into input (X) and output (y) variables
X = df.drop(columns=['target']).values
y = df['target'].values

# Function to create model, required for KerasClassifier
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(12, input_dim=13, activation='relu'))
	model.add(Dense(1, activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=1)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
param_grid = {'batch_size': [10, 20, 40, 60, 80, 100],
              'epochs': [20]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X, y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

/home/seek/anaconda3/envs/U4-S2-NNF/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Epoch 1/20
202/202 [==============================] - 0s 2ms/step - loss: 2.4046 - acc: 0.5446
Epoch 2/20
202/202 [==============================] - 0s 209us/step - loss: 2.2560 - acc: 0.5941
Epoch 3/20
202/202 [==============================] - 0s 215us/step - loss: 2.1839 - acc: 0.5842
Epoch 4/20
202/202 [==============================] - 0s 186us/step - loss: 1.8579 - acc: 0.5693
Epoch 5/20
202/202 [==============================] - 0s 205us/step - loss: 1.8218 - acc: 0.6089
Epoch 6/20
202/202 [==============================] - 0s 181us/step - loss: 1.6124 - acc: 0.5693
Epoch 7/20
202/202 [==============================] - 0s 181us/step - loss: 1.4669 - acc: 0.5990
Epoch 8/20
202/202 [==============================] - 0s 207us/step - loss: 1.4916 - acc: 0.5842
Epoch 9/20
202/202 [==============================] - 0s 176us/step - loss: 1.2866 - acc: 0.6386
Epoch 10/20
202/202 [==============================] - 0s 180us/step - loss: 1.2335 - acc: 0.6584
Epoch 11/20
202/202 [==========

In [ ]:
# define the grid search parameters
param_grid = {'batch_size': [80, 100],
              'epochs': [20, 40, 60]}

# Create Grid Search
grid = GridSearchCV(estimator=model, cv=10, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X, y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Epoch 1/20
272/272 [==============================] - 1s 3ms/step - loss: 7.3266 - acc: 0.5074
Epoch 2/20
272/272 [==============================] - 0s 50us/step - loss: 6.7324 - acc: 0.5074
Epoch 3/20
272/272 [==============================] - 0s 40us/step - loss: 5.6780 - acc: 0.5221
Epoch 4/20
272/272 [==============================] - 0s 40us/step - loss: 4.3816 - acc: 0.5625
Epoch 5/20
272/272 [==============================] - 0s 29us/step - loss: 3.3050 - acc: 0.6103
Epoch 6/20
272/272 [==============================] - 0s 40us/step - loss: 2.5618 - acc: 0.6213
Epoch 7/20
272/272 [==============================] - 0s 36us/step - loss: 2.5081 - acc: 0.6213
Epoch 8/20
272/272 [==============================] - 0s 39us/step - loss: 2.7016 - acc: 0.6103
Epoch 9/20
272/272 [==============================] - 0s 33us/step - loss: 2.7030 - acc: 0.6103
Epoch 10/20
272/272 [==============================] - 0s 36us/step - loss: 2.5236 - acc: 0.6250
Epoch 11/20
272/272 [===================